### ISSUE TITLE
Comida 

### ISSUE THREAD

**Issue by EstebanGL** [pdepjm/2024-tp0-presentacion-SofiaBaudo#1]
Que suerte y que mala suerte a la vez lo del premio de TikTok jaja. Ya que no sos fan de lo dulce, que comidas saladas si te gustan?

**Comment by SofiaBaudo** [comment]
Amo los pochoclos salados y los nachos!! Todo lo que es snack jajajajaj

**Comment by EstebanGL** [comment]
Uuuuh aguante los pochoclos salados
