### ISSUE TITLE
Suerte

### ISSUE THREAD

**Issue by BritosAylen** [pdepjm/2024-tp0-presentacion-SofiaBaudo#2]
Siempre me aparecen esos videos de Tiktok, que suerte que te toco a vos, pero que mal que era de cosas que no te gustaban

**Comment by SofiaBaudo** [comment]
A mi también siempre me aparecen! Es mas, seguí a unos tiktokers que regalan ropa(king of the kongo) para ganarme algo pero no lo conseguí :( No siempre tengo suerte jajjaja
